CHANGELOG.md
LICENSE
pubspec.yaml

Updates to CHANGELOG, LICENSE and pubspec files

WIP Updated CHANGELOG, pubspec and LICENSE files

---

android/build.gradle
android/src/main/kotlin/io/didomi/fluttersdk/DidomiPlugin.kt
example/ios/Podfile.lock
example/lib/main.dart
ios/Classes/SwiftDidomiSdkPlugin.swift
ios/didomi_sdk.podspec
lib/didomi_sdk.dart
test/didomi_sdk_test.dart

- Update sdk versions
- In the sample, propose a solution to avoid interaction with application while notice is displayed
- Perform some TODO (remove methods and accesses)

Prevent interaction with UI when notice is displayed

---

README.md

add integration tests documentation

---

example/integration_test/extensions/string_extension.dart
example/integration_test/purpose_test.dart
example/integration_test/util/assertion_helper.dart
example/integration_test/util/scroll_helper.dart
example/integration_test/vendor_test.dart
example/lib/testapps/sample_for_vendor_tests.dart

Added integration tests to cover methods that return the new Vendor type.

Added integration tests for vendor scenarios

---

example/integration_test/user_li_for_purpose_test.dart
example/integration_test/user_li_for_vendor_test.dart
example/ios/Podfile.lock
ios/didomi_sdk.podspec

Relates to CMP-1127
Cleanup legitimate interest UI tests

cleanup legitimate interest scenarios

---

example/integration_test/purpose_test.dart
example/integration_test/user_li_test.dart
example/integration_test/util/scroll_helper.dart
example/integration_test/vendor_test.dart

Relates to CMP-1127
add offset y as parameter for scroll util

add offset y as parameter for scroll util

---

example/integration_test/purpose_test.dart
example/integration_test/vendor_test.dart
example/lib/extensions/list.dart
example/lib/extensions/map.dart
example/lib/extensions/splay_tree_map.dart
example/lib/widgets/get_disabled_purpose_ids.dart
example/lib/widgets/get_disabled_purposes.dart
example/lib/widgets/get_disabled_vendor_ids.dart
example/lib/widgets/get_disabled_vendors.dart
example/lib/widgets/get_enabled_purpose_ids.dart
example/lib/widgets/get_enabled_purposes.dart
example/lib/widgets/get_enabled_vendor_ids.dart
example/lib/widgets/get_enabled_vendors.dart
example/lib/widgets/get_required_purpose_ids.dart
example/lib/widgets/get_required_purposes.dart
example/lib/widgets/get_required_vendor_ids.dart
example/lib/widgets/get_required_vendors.dart
example/lib/widgets/get_text.dart

Relates to CMP-1127
Create and use extensions for:
- Map
- List (String, Vendor, Purpose)

create and use extensions

---

android/src/main/kotlin/io/didomi/fluttersdk/DidomiPlugin.kt
example/integration_test/text_test.dart
example/integration_test/util/constants.dart
ios/Classes/SwiftDidomiSdkPlugin.swift

align getJavaScriptForWebView for both native sdks

---

.github/workflows/publish.yml
.github/workflows/update.yml

enable workflows

---

.github/scripts/uitests_for_ios.sh
.github/workflows/build.yml
.github/workflows/test.yml
.github/workflows/update.yml
android/build.gradle
android/src/main/kotlin/io/didomi/fluttersdk/DidomiEventStreamHandler.kt
android/src/main/kotlin/io/didomi/fluttersdk/DidomiPlugin.kt
android/src/main/kotlin/io/didomi/fluttersdk/EntitiesHelper.kt
example/integration_test/get_user_status_test.dart
example/integration_test/util/assertion_helper.dart
example/ios/Podfile.lock
example/lib/events_helper.dart
example/lib/main.dart
example/lib/testapps/sample_for_get_user_status_tests.dart
example/lib/widgets/base_sample_widget_state.dart
example/lib/widgets/get_user_status_other_info.dart
example/lib/widgets/get_user_status_purposes.dart
example/lib/widgets/get_user_status_vendors.dart
ios/Classes/DidomiEventStreamHandler.swift
ios/Classes/EntitiesHelper.swift
ios/Classes/SwiftDidomiSdkPlugin.swift
ios/didomi_sdk.podspec
lib/didomi_sdk.dart
lib/entities/entities_helper.dart
lib/entities/user_status.dart
lib/events/event_listener.dart
lib/events/events_handler.dart

Update Android SDK to 1.46.2.
Update iOS SDK to 1.58.0.
Versions may be updated later if important fixes are released.
Expose getUserStatus method from native sdks, deprecate old user status methods.
Update tests.

Update sdks and expose getUserStatus method

---

lib/parameters/user_auth_params.dart

Some UserStatusAuthParams fields were incorrectly optional

Make UserStatusAuthParameter fields mandatory

---

CHANGELOG.md
android/build.gradle
android/src/main/kotlin/io/didomi/fluttersdk/DidomiPlugin.kt
example/ios/Podfile.lock
example/lib/widgets/initialize.dart
ios/didomi_sdk.podspec
lib/didomi_sdk.dart
pubspec.yaml

Closes: CMP-2343
Add AndroidTV specific parameters support
Update native SDKs
Update minor version

CMP-2343 android tv support

---

.github/scripts/check_before_update.sh
.github/scripts/extract_android_sdk_version.sh
.github/scripts/extract_ios_sdk_version.sh
.github/scripts/update_bridge_version.sh
.github/scripts/update_changelog.sh
.github/workflows/release.yml
CHANGELOG.md

- mention native SDKs version in the release notes
- better change log formatting

Update release scripts

---

CHANGELOG.md
android/build.gradle
example/integration_test/set_user_test.dart
example/ios/Podfile.lock
ios/didomi_sdk.podspec
pubspec.yaml

- Update native SDKs version
- Revert Android skipped scenario for setUser
- Increment version
- Update change log

Update native SDKs + Prepare new release

---

.github/workflows/update.yml
CHANGELOG.md
android/build.gradle
android/src/main/kotlin/io/didomi/fluttersdk/DidomiEventStreamHandler.kt
example/ios/Podfile.lock
example/lib/events_helper.dart
ios/Classes/DidomiEventStreamHandler.swift
ios/didomi_sdk.podspec
lib/events/event_listener.dart
lib/events/events_handler.dart
pubspec.yaml

- Update native SDKs
- Implement new internal events for SPI screens
- Increment Bridge minor version
- Edit change log
- Update Github Action plugins

CMP-3385 new SPI events

---

.github/workflows/release.yml
.github/workflows/tag.yml
.github/workflows/update.yml

This is the workflows order when we only need to update native SDKs:
1. update.yml (will get native sdks version + increment bridge version + trigger tag.yml)
2. tag.yml (will get the new bridge version + create tag from bridge version)
3. release.yml (triggered by the new tag > run tests + create release from tag name)
4. publish.yml (triggered by the new release > publish bridge)

CMP-3552 release workflow

---

ios/Classes/DidomiEventStreamHandler.swift

Fix for https://github.com/didomi/flutter/issues/89

Apply fix to avoid error "channel sent a message from native to Flutter on a non-platform thread

---

android/build.gradle
example/integration_test/get_user_status_test.dart
example/ios/Podfile.lock
example/lib/widgets/get_user_status_other_info.dart
ios/didomi_sdk.podspec
lib/entities/user_status.dart

expose new property `didomi_dcs` trough `getUserStatus` method

expose new property `didomi_dcs` 

---

android/src/main/kotlin/io/didomi/fluttersdk/DidomiPlugin.kt
example/integration_test/consent_state_test.dart
example/lib/widgets/check_consent.dart
ios/Classes/SwiftDidomiSdkPlugin.swift
lib/didomi_sdk.dart

Implement `shouldUserStatusBeCollected` function and use it from consent state plugin and tests

CMP-4274 Implement `shouldUserStatusBeCollected`

---

example/integration_test/consent_state_test.dart
ios/Classes/SwiftDidomiSdkPlugin.swift

Do throw didomi not ready exception for iOS function:
- shouldConsentBeCollected
- shouldUserStatusBeCollected
- isConsentRequired,
- isUserConsentStatusPartial
- isUserLegitimateInterestStatusPartial
- isUserStatusPartial
- hideNotice
- isNoticeVisible
- hidePreferences
- isPreferencesVisible

CMP4431 - do throw didomi not ready exception

---

.github/workflows/build.yml
.github/workflows/publish.yml
.github/workflows/release.yml
.github/workflows/tag.yml
.github/workflows/test.yml
.github/workflows/update.yml

Update plugins to use node 20 instead of 16 from workflows

Update plugins to use node 20 instead of 16

---

CHANGELOG.md
android/build.gradle
example/ios/Podfile.lock
ios/didomi_sdk.podspec
pubspec.yaml

- Increment minor version
- Update change log with new functions

Update minor version and change log

---

CHANGELOG.md
android/build.gradle
example/integration_test/vendor_test.dart
example/ios/Podfile.lock
example/lib/widgets/get_vendor.dart
ios/didomi_sdk.podspec
lib/entities/vendor.dart
pubspec.yaml

- Update iOS native SDK version
- Update Changelog for bridge version 2.0.0

Update last native sdk versions and changelog

---

CHANGELOG.md
android/build.gradle
example/ios/Podfile.lock
ios/didomi_sdk.podspec
lib/events/events_handler.dart
pubspec.yaml

Fixes: https://github.com/didomi/flutter/issues/105

CMP-4559 event on preferences click disagree to all

---

android/build.gradle
android/src/main/kotlin/io/didomi/fluttersdk/DidomiEventStreamHandler.kt
android/src/main/kotlin/io/didomi/fluttersdk/DidomiPlugin.kt
android/src/main/kotlin/io/didomi/fluttersdk/EntitiesHelper.kt
example/integration_test/vendor_status_listener_test.dart
example/ios/Podfile.lock
example/lib/events_helper.dart
example/lib/main.dart
example/lib/widgets/sdk_events_logger.dart
ios/Classes/DidomiEventStreamHandler.swift
ios/Classes/EntitiesHelper.swift
ios/Classes/SwiftDidomiSdkPlugin.swift
ios/didomi_sdk.podspec
lib/didomi_sdk.dart
lib/events/events_handler.dart

- Update native Android and iOS sdks
- Handle new methods `addVendorStatusListener` / `removeVendorStatusListener`

Add support for vendor status listener

---

CHANGELOG.md
android/build.gradle
example/android/build.gradle
example/ios/Podfile.lock
ios/didomi_sdk.podspec
pubspec.yaml

- Update native SDKs
- Update bridge version
- Update changelog

Prepare 2.1.0 release

---

android/build.gradle
android/src/main/kotlin/io/didomi/fluttersdk/DidomiEventStreamHandler.kt
android/src/main/kotlin/io/didomi/fluttersdk/DidomiPlugin.kt
example/android/app/build.gradle
example/integration_test/set_user_test.dart
example/ios/Podfile.lock
example/ios/Runner.xcodeproj/project.pbxproj
example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
example/lib/events_helper.dart
example/lib/testapps/sample_for_set_user_tests.dart
ios/Classes/DidomiEventStreamHandler.swift
ios/Classes/SwiftDidomiSdkPlugin.swift
ios/didomi_sdk.podspec
lib/didomi_sdk.dart
lib/events/event_listener.dart
lib/events/events_handler.dart
lib/events/sync_ready_event.dart

Changes included:
- Added support for the Sync Ready event.
- Improved the code used to get the root view controller on iOS.

CMP-4651: implemented Sync Ready event

---

.github/scripts/uitests_for_ios.sh
android/src/main/kotlin/io/didomi/fluttersdk/DidomiPlugin.kt
example/integration_test/initialize_with_success_test.dart
example/lib/widgets/initialize.dart
ios/Classes/SwiftDidomiSdkPlugin.swift
lib/didomi_sdk.dart

Added support for overriding country and region codes when initializing the SDK.

CMP-4660: added support for country and region override

---

CHANGELOG.md
android/build.gradle
android/src/main/kotlin/io/didomi/fluttersdk/DidomiPlugin.kt
example/integration_test/initialize_with_success_test.dart
example/integration_test/set_user_test.dart
example/ios/Podfile.lock
example/lib/widgets/set_user.dart
example/lib/widgets/transactions/chains/chain_disable_purpose_transactions.dart
example/lib/widgets/transactions/chains/chain_disable_vendor_transactions.dart
example/lib/widgets/transactions/chains/chain_enable_purpose_transactions.dart
example/lib/widgets/transactions/chains/chain_enable_vendor_transactions.dart
ios/Classes/SwiftDidomiSdkPlugin.swift
ios/didomi_sdk.podspec
lib/didomi_sdk.dart
lib/parameters/user_auth_params.dart
pubspec.yaml

- Run dart fixes
- Use Json for `setUser` params
- Update Native SDKs
- Implement new optional parameter `synchronizedUsers` for `setUser` function
- Add new tests
- Increment minor version and update change log prior to new release

CMP-4657 - Implement new param for setUser function

---

example/integration_test/get_user_status_test.dart
example/integration_test/set_user_test.dart
example/lib/events_helper.dart
example/lib/widgets/check_consent.dart
example/lib/widgets/get_required_purpose_ids.dart
example/lib/widgets/get_required_vendor_ids.dart
example/lib/widgets/get_user_status_other_info.dart
example/lib/widgets/get_user_status_purposes.dart
example/lib/widgets/get_user_status_vendors.dart
example/lib/widgets/set_user.dart
example/lib/widgets/set_user_status.dart
lib/didomi_sdk.dart
lib/events/event_listener.dart

Update Deprecated status for some methods, following https://developers.didomi.io/cmp/mobile-sdk/android/reference/api/deprecated

Update Deprecated status for methods

---

android/src/main/kotlin/io/didomi/fluttersdk/DidomiPlugin.kt
example/integration_test/vendor_test.dart
example/lib/main.dart
example/lib/testapps/sample_for_vendor_tests.dart
example/lib/widgets/get_vendor_count.dart
ios/Classes/SwiftDidomiSdkPlugin.swift
lib/didomi_sdk.dart

Add support for vendor count functions:
- `getTotalVendorCount()`
- `getIabVendorCount()`
- `getNonIabVendorCount()`

Handle vendor count functions

---

android/build.gradle
android/src/main/kotlin/io/didomi/fluttersdk/DidomiEventStreamHandler.kt
example/integration_test/set_user_test.dart
example/ios/Podfile.lock
ios/didomi_sdk.podspec

- Update native Android and iOS SDKs to version 2.17.0
- Fix build issue on Android

Update native SDK versions to 2.17.0
